package se.yrgo.dataaccess;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;
import se.yrgo.services.customers.CustomerNotFoundException;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private JdbcTemplate jdbcTemplate;

    // Create tables
    private static final String CREATE_CUSTOMER_TBL_SQL = "create table CUSTOMER(CUSTOMER_ID VARCHAR(20), COMPANY_NAME VARCHAR(50), EMAIL VARCHAR(30), TELEPHONE VARCHAR(20), NOTES VARCHAR(300))";
    private static final String CREATE_CALL_TBL_SQL = "create table RING(CALL_ID integer generated by default as identity (start with 1), TIME_DATE DATETIME2, NOTES VARCHAR(300), CUSTOMER_ID VARCHAR(20))";

    // SQL queries
    private static final String INSERT_CUSTOMER_SQL = "insert into CUSTOMER(CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) values (?, ?, ?, ?, ?)";
    private static final String GET_CUSTOMER_BY_ID_SQL = "select * from CUSTOMER where CUSTOMER_ID=?";
    private static final String GET_CUSTOMERS_BY_NAME_SQL = "select * from CUSTOMER where COMPANY_NAME=?";
    private static final String UPDATE_CUSTOMER_SQL = "UPDATE CUSTOMER SET CUSTOMER_ID=?, COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String DELETE_CUSTOMER_SQL = "delete from CUSTOMER where CUSTOMER_ID=?";
    private static final String GET_ALL_CUSTOMERS_SQL = "select * from CUSTOMER";
    private static final String GET_FULL_CUSTOMER_DETAIL_SQL = "";
    private static final String ADD_CALL_SQL = "insert into RING(TIME_DATE, NOTES, CUSTOMER_ID) values (?, ?, ?)";


    public CustomerDaoJdbcTemplateImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void createTables() {
        try {
            this.jdbcTemplate.update(CREATE_CUSTOMER_TBL_SQL);
            this.jdbcTemplate.update(CREATE_CALL_TBL_SQL);
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Customer and/or Call tables may already exist");
        }
    }

    @Override
    public void create(Customer customer) {
        jdbcTemplate.update(INSERT_CUSTOMER_SQL, customer.getCustomerId(), customer.getCompanyName(), customer.getEmail(), customer.getTelephone(), customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) {
        return jdbcTemplate.queryForObject(GET_CUSTOMER_BY_ID_SQL, new CustomerMapper(), customerId);
    }

    @Override
    public List<Customer> getByName(String name) {
        return this.jdbcTemplate.query(GET_CUSTOMERS_BY_NAME_SQL, new CustomerMapper(), name);
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        this.jdbcTemplate.update(UPDATE_CUSTOMER_SQL, customerToUpdate.getCustomerId(), customerToUpdate.getCompanyName(), customerToUpdate.getEmail(), customerToUpdate.getTelephone(), customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        this.jdbcTemplate.update(DELETE_CUSTOMER_SQL, oldCustomer.getCustomerId());
    }

    @Override
    public List<Customer> getAllCustomers() {
        return this.jdbcTemplate.query(GET_ALL_CUSTOMERS_SQL, new CustomerMapper());
    }


    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {


        return null;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        this.jdbcTemplate.update(ADD_CALL_SQL, newCall.getTimeAndDate(), newCall.getNotes(), customerId);
    }

    class CustomerMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNumber) throws SQLException {
            String customerId = rs.getString("CUSTOMER_ID");
            String companyName = rs.getString("COMPANY_NAME");
            String email = rs.getString("EMAIL");
            String telephone = rs.getString("TELEPHONE");
            String notes = rs.getString("NOTES");
            Customer customer = new Customer(customerId, companyName, email, telephone, notes);
            return customer;
        }
    }
}
