package se.yrgo.dataaccess;

import org.springframework.jdbc.core.JdbcTemplate;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private JdbcTemplate jdbcTemplate;
    private static final String CREATE_CUSTOMER_TBL_SQL = "create table CUSTOMER_TBL(CUSTOMER_ID VARCHAR(20), COMPANY_NAME VARCHAR(50), EMAIL VARCHAR(30), TELEPHONE VARCHAR(20), NOTES VARCHAR(300)";
    private static final String CREATE_CALL_TBL_SQL = "create table CALL_TBL(CALL_ID integer generated by default as identity (start with 1), TIME_DATE DATETIME2, NOTES VARCHAR(300)";

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void createTables() {
        try {
            this.jdbcTemplate.update(CREATE_CUSTOMER_TBL_SQL);
            this.jdbcTemplate.update(CREATE_CALL_TBL_SQL);
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Customer and/or Call tables may already exist");
        }
    }

    @Override
    public void create(Customer customer) {

    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        return null;
    }

    @Override
    public List<Customer> getByName(String name) {
        return List.of();
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {

    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {

    }

    @Override
    public List<Customer> getAllCustomers() {
        return List.of();
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        return null;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {

    }
}
